### ISSUE TITLE
Using a template for MnM Subscription-editing / Variable UI, would be best for plugin customization, and plugin upgrades

### ISSUE THREAD

**Issue by limist** [kathyisawesome/wc-mnm-subscription-editing#22]
Similar to the issue logged for wc-mnm-variable here: https://github.com/kathyisawesome/wc-mnm-variable/issues/25

When on the /my-account/view-subscription/123 page, having everything within the main tbody of the main table.shop_table in an overridable template will help ease customization (often shops need more specific terms to ease and speed customer understanding of the UI), and ease plugin upgrading.

The UI elements that would be better off in a template include:

1. The initial "Update Selections" button; the text would often need to be changed to be more domain-specific
2. Upon the editing UI finishing loading, the "Edit selections for.." h3 
3. Attribute name string (assuming it's checked in wp-admin as "Used for variations")
4. the Variation selector, currently a drop-down menu (e.g. maybe radio buttons would be better sometimes?)
5. the "Clear" link above the Variation selector (e.g. may not always want to show this)
6. Variation description/text
7. Variation price
8. the "Choose selections" instructional text
9. Category name (if the MnM option of "Allowed content" and "Select product categories" was chosen in the wp-admin side)
10. The table used to list the products (e.g. sometimes the table headers' text of "Product" should be changed)

HTH, thanks!

**Comment by helgatheviking** [comment]
Kai, are there any templates specific to this editing plugin that you feel you need better access to? All the variable/variation templates are over in the VMM plugin.

**Comment by limist** [comment]
@helgatheviking Ah, if the templates are all in VMM for the UI mentioned above, then the answer to your q is no.  :-)
