### ISSUE TITLE
Increment/decrement button clicks don't work, when editing a subscription MnM variable product

### ISSUE THREAD

**Issue by limist** [kathyisawesome/wc-mnm-subscription-editing#24]
@helgatheviking On our test server, after purchasing a [subscription MnM variable product](https://env-goleafside-test.kinsta.cloud/product/subscription/?mnm_quantity%5B669%5D=1&mnm_quantity%5B610%5D=1&mnm_quantity%5B662%5D=1&mnm_quantity%5B49584%5D=1&mnm_quantity%5B607%5D=1&mnm_quantity%5B612%5D=1&mnm_quantity%5B625%5D=1&mnm_quantity%5B620%5D=1&mnm_quantity%5B10129%5D=1&mnm_quantity%5B673%5D=1&mnm_quantity%5B10134%5D=1&mnm_quantity%5B613%5D=1&mnm_quantity%5B100329%5D=1&mnm_quantity%5B670%5D=1&mnm_quantity%5B8250%5D=1&mnm_quantity%5B616%5D=1&mnm_quantity%5B45344%5D=1&mnm_quantity%5B645%5D=1&mnm_quantity%5B652%5D=1&mnm_quantity%5B648%5D=1) and then going to the corresponding My Account > View Subscription page, clicking the blue "Update Bundle" button, clicking the - or + buttons on any product/meal row has no effect initially.  

Strangely, those buttons DO start working after changing the variation/bundle.

But if one then changes the variation back to the original one, the buttons stop working again.

**Comment by limist** [comment]
Clicking into a product/meal's quantity field, and manually changing it, does seem to work normally.

**Comment by helgatheviking** [comment]
Reminder the plus/minus buttons are from your theme. Didn't I generate a code snippet for compatibility? Is that snippet in use on your site? I don't see the Code Snippets plugin active and I checked the theme.

**Comment by helgatheviking** [comment]
I installed the snippet and then found that i had since renamed the custom jquery event. so I've updated the snippet to the following:
```
/**
 * Flatsome plus/minus buttons
 * Initialize for Variable Mix and Match and Subscription editing
 */
function flatsome_plus_minus_mnm_script() {
   wp_add_inline_script( 'flatsome-theme-woocommerce-js', '
      jQuery(document).on( "wc_mnm_variation_form_loaded", function() {
         jQuery(this).find(".variable_mnm_form .child-item .quantity").addQty();
      } );
   ' );
}
add_action( 'wp_enqueue_scripts', 'flatsome_plus_minus_mnm_script', 101 );
```

Seems to work for me on editing, please check.

**Comment by limist** [comment]
@helgatheviking Yes, the buttons work again, for both the main Product page, and in the edit-subscription UI, thanks!
