### ISSUE TITLE
After editing/updating a MnM variable product subscription, saving/update doesn't complete

### ISSUE THREAD

**Issue by limist** [kathyisawesome/wc-mnm-subscription-editing#25]
@helgatheviking After editing the quantities of an MnM variable subscription, then clicking the orange "Update subscription" button in the (MnM Mobile Styles) footer, the spinner is then seen...and just keeps spinning indefinitely.  Not seeing a console error.

**Comment by helgatheviking** [comment]
Anything else you did to trigger this issue? I cannot reproduce yet.

**Comment by limist** [comment]
@helgatheviking I'm also not seeing this issue at the moment, strange.  Will test further and update, thanks.

**Comment by limist** [comment]
@helgatheviking I think I've found how to reproduce this: From the view-subscription page, click the "Update Bundle" button and then change the variation, e.g. to a larger one.  Then update the quantities of one or more items to satisfy the larger variation's size; then try clicking "Update subscription" in the Mobile Styles footer; the spinner appears and stays there.

**Comment by helgatheviking** [comment]
@limist Thanks, I see this now. It's like the click on the mobile footer isn't relaying the click to the original (if now hidden) add to cart button. I'll have to check on that tomorrow.

**Comment by helgatheviking** [comment]
I re-installed the latest version of the mobile styles and it seems to be working now. Can you check?

**Comment by limist** [comment]
@helgatheviking That test-case of upsizing and then saving, now seems to work, thanks!

I wanted to also test downsizing and saving, but am running into a different bug; will open a separate issue for it...done, here: https://github.com/kathyisawesome/wc-mnm-subscription-editing/issues/27

**Comment by limist** [comment]
@helgatheviking I'm still seeing this bug, this time when editing a freshly purchased subscription-bundle, and keeping the same variation (don't upsize nor downsize), if I zero out one item (e.g. decrement quantity from 1 to 0), then add more of another item (increment quantity from 1 to 2), and click the big orange Update Subscription button, the spinner is seen and just keeps spinning forever.  No errors seen in Console.

Similarly, upsizing and then saving doesn't work either, trying to update/save shows the spinner that just keeps going.  Clicking Cancel Edit breaks out of that stuck state.
