### ISSUE TITLE
When downsizing to a smaller MnM container, UI prevents decrementing & editing to smaller quantities

### ISSUE THREAD

**Issue by limist** [kathyisawesome/wc-mnm-subscription-editing#27]
@helgatheviking When editing a subscription, and after having upsized the subscription to a larger MnM variation/container, there looks to be a UI bug:

- From the view-subscription page, click the Update Bundle button
- Select a smaller variation than before
- To satisfy the lower items count, try clicking any of the -/decrement buttons; the red tooltip flashes e.g. "Container limited to 20" and prevents the decrement from working.
- Trying to directly edit the quantity field of any item to a smaller or zero quantity, brings up the same red tooltip, and immediately resets to the original value.

Thus it's impossible for the user to downsize their subscription.

**Comment by limist** [comment]
@helgatheviking  On this same use-case, it would be helpful to have the Mobile Styles footer give some feedback (e.g. instructions, red progress bar) for this over-filled case, to make it clear to the user to lower the items count.  Thanks!

**Comment by limist** [comment]
Quick update that this problem also appears in the wp-admin backend, for the case when one of our support staff would want to downsize and edit the smaller variation's quantities — can't do so, UI red tooltip blocks all attempts to decrement.

**Comment by helgatheviking** [comment]
Thanks @limist I think this is a 2 part problem 1. core MNM needs a better way to get out of this situation. That's why mostly for core i've tried to make it impossible to get _in to_ this overfilled state. and 2. I think the JS-prefilling may be related to this... need to try to smooth that out.

**Comment by helgatheviking** [comment]
@limist I believe we are clearing selections on downsize now to prevent this. Is this still an issue?
