### ISSUE TITLE
How to customize text etc in element tr.mnm_table_container ?

### ISSUE THREAD

**Issue by limist** [kathyisawesome/wc-mnm-subscription-editing#29]
In the my-account/view-subscription page when showing an MnM-variable subscription, I'd like to customize some of the text in the first row, and was wondering if there's a way to do that with template overrides? i.e. without touching the original wc-mnm-subscription-editing plugin's files.

e.g. it looks like this currently:

![image](https://github.com/kathyisawesome/wc-mnm-subscription-editing/assets/138796/23c6d642-8177-47a7-bf88-f8817dc56971)

In the above, I'd want to get rid of the "Meal" and "Subtotal" table headers; and get rid of the redundant text "LeafSide Subscription Bundles..." for a cleaner appearance.

Thanks in advance for any advice!

**Comment by limist** [comment]
Similarly, after clicking/loading the UI to update an MnM subscription, is there a clean way to customize that UI?

e.g. 
![image](https://github.com/kathyisawesome/wc-mnm-subscription-editing/assets/138796/9fcf4f6e-7157-4652-9394-f6ed3029da3a)

In the above, I'd want to remove the "Meal" and "Subtotal" headers again, remove the "Edit selections for ..." text.  TIA!

**Comment by limist** [comment]
@helgatheviking If an overridable template would take too long, one solution would be to wrap all those elements in divs having unique id or class, to make it easy to hide them via CSS alone.  

e.g. in the view-subscription UI (before the update button is clicked), in the tr.mnm_table_container element, in td.product-name, the MnM product name's text is right after that td element, without being wrapped by a div; if it was wrapped with a div and unique id, easy-peasy to hide it.

Thanks!

**Comment by helgatheviking** [comment]
Kai, 

It looks like you've already customized the order/shop table header from Product to Meal

![image](https://github.com/kathyisawesome/wc-mnm-subscription-editing/assets/507025/0d2c984c-3a11-4533-9d35-1b19b2b8eea7)

These aren't generated by me, but I do leave them in place when you are editing the subscription. I do add a CSS class when in editing mode and you can use that to target the table header

```
.wc-mnm-subscription-editing .order_details thead {
	display: none;
}
```

"Leafside Subscription Bundles - Plant-powered Pivot [30 meals]" is the [order item name](https://github.com/woocommerce/woocommerce/blob/66f852fc267bcbee33d786db6adb4fa875c6bdd7/plugins/woocommerce/templates/order/order-details-item.php#L33), which is saved for the selected variation. You could possibly reduce the length of the variation titles and it might reduce the length of the entire bundle variation title. It looks like there's also a filter `woocommerce_order_item_name` though targeting this only when editing could be tough.

**Comment by limist** [comment]
@helgatheviking Thanks, you're right about that first point, forgot that I had customized with a template override file, woocommerce/myaccount/subscription-totals.php

For the order item name, I used some CSS to hide it, thanks.
