### ISSUE TITLE
Add product hyperlinks to the subscription-editing UI, unlink images

### ISSUE THREAD

**Issue by limist** [kathyisawesome/wc-mnm-subscription-editing#31]
@helgatheviking After clicking the Update button and having the MnM subscription-editing UI load, I noticed that in the table listing all the products and quantities, the product images on the left-hand-side are unexpectedly linked (going to the larger version of itself on uploads/) which is user-unfriendly since an accidental click kicks them out of the subscription-editing UI.  I think it would be best to unlink all of those, or, link to their product pages with a target attribute, so they open in a new tab.

Similarly, each product name would benefit from being hyperlinked to its respective product page, with a target attribute to open in a new tab, so that the user can stay in the editing UI and continue changing quantities of products in the MnM container.

It looks like the file that generates this table is,
wc-mnm-subscription-editing/assets/js/frontend/wc-mnm-subscription-editing.js

Thanks!

**Comment by limist** [comment]
@helgatheviking Thanks, updating the subscription-editing plugin to rc7 results in the image link being removed, and that'll help reduce user confusion/surprise.  👍 

What would you suggest doing to hyperlink the product name, to open in a new tab please?  (the  main MnM product page has this behavior) Is there a php file to override, or would this be another JS-level change?  Thanks!

**Comment by helgatheviking** [comment]
>the main MnM product page has this behavior

Interesting... it should probably _not_ have this behavior as I know new tabs tend to be less accessible to folks who navigate with a keyboard. Pretty sure my accessibility auditors brought that up.

So in the My Account area, it looks like [there are NO links](https://github.com/kathyisawesome/wc-mnm-subscription-editing/blob/trunk/wc-mnm-subscription-editing.php#L433)? I think that's best, but you want to bring the links back?

**Comment by limist** [comment]
@helgatheviking In the My Account area, view-subscription, the initial display of products in the MnM-subscription DO have hyperlinked product names.  But after clicking the Update Bundle button, to reach the editing-UI, the list of all available categories/products show unlinked, plain-text product names.

I'd argue that in that editing context, it makes sense to hyperlink product names because people often need a reminder as to some details of products they want, thanks!

**Comment by helgatheviking** [comment]
Well it looks like it's a single line, so should be fairly simple to switch it off. I'm not sure I agree though as opening up a new tab can make it difficult to come back to the editing process. But since you're really the primary user of this plugin, I'll let you pick the default.

**Comment by limist** [comment]
@helgatheviking Thanks for the update; I think most users will know how to get back to the editing UI, as opening in a new tab is a common behavior.  Also, given how 2/3 to 3/4 of web traffic is mobile these days, imho keyboard-only navigation is relatively rare. Thanks in advance for any updated code to test.

**Comment by helgatheviking** [comment]
Keyboard only nav _is_ rare, but it's an accessibility thing for folks who can't see the screen. But since we're doing it on the main page it's not a big deviation.

I have no Wi-Fi at my team's hotel so not sure I'll be getting to this. I pointed out the line in question... You can comment it out to test if you'd like.

**Comment by limist** [comment]
@helgatheviking Which line in the code are you referring to please?  Not seeing one in the latest commit or comments above, thanks.

**Comment by helgatheviking** [comment]
https://github.com/kathyisawesome/wc-mnm-subscription-editing/blob/trunk/wc-mnm-subscription-editing.php#L433

**Comment by limist** [comment]
This issue was fixed in MnM Variations 1.0.0-rc.16 thanks @helgatheviking
