### ISSUE TITLE
Plugin causes newlines to appear in all output

### ISSUE THREAD

**Issue by Meryl** [kathyisawesome/wc-mnm-subscription-editing#32]
The php files in the includes folder have empty lines before the opening php-tag, causing newlines to appear in all output. Not a huge problem for most projects, but it's annoying when using WP-CLI and it can mess up certain XML-based responses.

**Comment by helgatheviking** [comment]
Hi Tim, thanks for reporting this! I've fixed it and it will get into the next tagged release. 

If you don't mind, I am curious how you ended up finding this project?

**Comment by Meryl** [comment]
Hey Kathy, one of our clients' website uses this plugin. We did not develop this website, so sadly I'm not able to tell you how it got in there. I just found that a certain request was failing because of malformed xml (it didn't like the whitespace before the response body), and tracked it down to those two specific files.
