### ISSUE TITLE
Upon clicking again to edit an MnM subscription, the incorrect browser alert/pop-up is seen (re. container size change)

### ISSUE THREAD

**Issue by limist** [kathyisawesome/wc-mnm-subscription-editing#34]
After buying/starting an MnM Variable product subscription, and navigating to the corresponding /my-account/view-subscription/ page, I found that:

- The 1st click on the button to update the next subscription order worked as expected; i.e. I can update quantities of items; and can change variation with the expected browser alert/pop-up. (Which correctly displays "Your chosen container size has changed so your selections have been reset.")

- But the 2nd and subsequent clicks to update the subscription (without reloading the view-subscription page) behaved differently: The browser alert/pop-up immediately and incorrectly appears, telling the user that same sentence about a container change (which didn't actually happen) and selections reset.   Fortunately, the user can click the Cancel Edit button (in the MnM Mobile Styles footer) and back out of that reset with no changes.  But that would be very confusing for a user.

Per Kathy's question, reloading the view-subscription page seems to reset the problem above: The 1st click (to update selections) after reloading works as expected without the initial incorrect alert/pop-up; but the 2nd and subsequent clicks shows the same initial incorrect alert/pop-up as mentioned above.

**Comment by limist** [comment]
@helgatheviking Noting that this issue/bug is also seen on the test server, thanks:  https://backcourt.instawp.xyz/my-account/view-subscription/387/

**Comment by helgatheviking** [comment]
I have isolated the problem to [here](https://github.com/kathyisawesome/wc-mnm-variable/blob/efe829163d0b5a50ed4fa40183efc4c048bae6a0/src/data/container/actions.js#L22-L29) in the variable product data store actions. 

Basically once the sub is updated the first time a `container` is loaded into the redux data store. It's not _cleared_ when the subscription is finished updating, so it's still set in the data store on the 2nd attempt to update. Either I should clear the data store OR check if the ID we're setting is the same as the current one in the store.

**Comment by helgatheviking** [comment]
@limist I believe I have fixed this in VMNM 2.0.3. Updated your staging site so you can test again.

**Comment by limist** [comment]
@helgatheviking Thanks, and yes, this looks to be fixed, no more incorrect browser alert.  👍
