### ISSUE TITLE
When editing a subscription, MnM Mobile Styles "Add to Cart" button text should change for subscription context

### ISSUE THREAD

**Issue by limist** [kathyisawesome/wc-mnm-subscription-editing#35]
When editing an existing MnM subscription, and also having the MnM Mobile Styles mini-plugin activated, the latter's footer button text should change to be clearer to the user: From the usual but not-quite-fitting "Add to Cart" to something fitting the subscription-editing context, like "Update Subscription" or "Save"

Relatedly, to be as clear as possible for non-technical users, the left-hand-side text of "You have selected X items. Update to continue..." should match whatever the text is on the update/save button.  Thanks!  🙏

**Comment by helgatheviking** [comment]
Good catch... it's def not supposed to say "Add to cart" here.

**Comment by helgatheviking** [comment]
Closed by https://github.com/kathyisawesome/wc-mnm-mobile-styles/commit/907599c1cab83ec44df9e141ca9cf2890b96658c
